import type { NextPage } from 'next'
import Link from 'next/link'
import BreadcrumbItem from 'components/atoms/BreadcrumbItem'
import Text from 'components/atoms/Text'
import Box from 'components/layout/Box'
import Flex from 'components/layout/Flex'
import Breadcrumb from 'components/molecules/Breadcrumb'
import Layout from 'components/templates/Layout'
import CartContainer from 'containers/CartContainer'
import {useAuthGuard} from 'utils/hooks'

